#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          confible
# Required-Start:    $network $local_fs $remote_fs $time
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# Author:  Ed Lafargue <ed@wizkers.io>
#

DESC="ConfiBLE configuration server"
DAEMON=`which node`
DAEMON_ARGS='/home/pi/rpibleconf/main.js'
#export DEBUG=wizkers:*,att

test -x $DAEMON || exit 0

case "$1" in
	start)
	log_begin_msg "Starting ConfiBLE"
        cd /home/pi/rpibleconf/
	# Export the NODE_PATH variable to tell node where to get its modules
	export NODE_PATH=.
	node main.js 2>&1 | logger -p local0.info &
	log_end_msg 0
	;;
	stop)
	;;
	restart|force-reload)
	$0 start
	;;
	status)
	$PROGRAM –show
	;;
	*)
	log_failure_msg "Usage: $PROGRAM {start|stop|restart|force-reload|status}"
	exit 1
esac

exit 


